apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata: 
  annotations: 
    ingress.kubernetes.io/allow-http: "false"
    ingress.kubernetes.io/ssl-redirect: "true"
    virtual-server.f5.com/ip: "10.192.75.106"
  name: prometheus-ui
  namespace: monitoring
spec: 
  backend: 
    serviceName: prometheus-service
    servicePort: 8080
  tls: 
  - secretName: /Common/clientssl
